### ISSUE TITLE
open command not found

### ISSUE THREAD

**Issue by radville** [learn-co-curriculum/git-workflow-merge-conflicts-lab#4]
In "From the master branch, run open index.html from your terminal... ", the command "open index.html" give the error "bash: open: command not found". The command httpserver works to open the page in a new tab.

**Comment by maxwellbenton** [comment]
Hi @radville,

Thank you for spotting this and providing feedback. We've updated the materials to mention `httpserver` first since most students are using the in-browser IDE. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
